# Generated by Django 3.2.15 on 2023-05-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mechanic',
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('four wheeler with auto-gear', 'four wheeler with auto-gear'), ('four wheeler with manual-gear', 'four wheeler with manual-gear')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
